version: "3.2.0"

services:
  react-app:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_DEV_BACKEND_URl=http://localhost:8000
  api:
    build: ./backend
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
